from database.db import fetch_engine
db = fetch_engine()

class ClassSession(db.Document):
    created_date = db.DateTimeField(required=True)
    modified_date = db.DateTimeField(required=True)
    class_session_id = db.UUIDField(required=True)
    class_id = db.UUIDField(required=True)
    instructor_id = db.UUIDField(required=True)
    student_id = db.UUIDField(required=True)
    location_id = db.UUIDField(required=True)
    offer_id = db.UUIDField(required=True)
    class_cost = db.FloatField(required=True)
    discount = db.FloatField(default=0, required=True)
    currency = db.StringField(default="USD")
    class_date = db.DateTimeField()
    status = db.StringField(default="Scheduled", required=True, choices=["Completed", "Scheduled"])
    duration = db.IntField(required=True, description = "number of minutes of the class")
    class_count = db.IntField(required=True, default=1)
    total = db.FloatField(required=True)
